---


version: "3"
services:
  Hub:
    image: selenium/hub
    ports:
     - 4444:4444
  chrome:
    image: selenium/node-chrome-debug
    ports:
     - 5901:5900
  firefox:
    image: selenium/node-firefox-debug
    ports:
     - 5902:5900
...
   
